# Generated by Django 4.0.4 on 2022-05-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroJuego',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idjuego', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripcion')),
                ('foto', models.CharField(max_length=20, verbose_name='Foto')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.generojuego')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
