# Generated by Django 4.0.4 on 2022-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_generojuego_juego_remove_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='foto',
        ),
        migrations.AddField(
            model_name='juego',
            name='caratula',
            field=models.ImageField(default=0, upload_to='files/caratulas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
