# Generated by Django 4.0.4 on 2022-05-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_remove_distribuidorajuego_fechacreaciondistribudora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidorajuego',
            name='fundacionDistribuidora',
        ),
    ]
