# Generated by Django 4.0.4 on 2022-05-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_remove_juego_distribuidora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='distribuidora',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalogos.distribuidorajuego'),
            preserve_default=False,
        ),
    ]
