# Generated by Django 4.0.1 on 2022-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_juego_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='añoSalida',
        ),
        migrations.AddField(
            model_name='juego',
            name='annoSalida',
            field=models.CharField(default=0, max_length=20, verbose_name='AnnoSalida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distribuidorajuego',
            name='logoDistribuidora',
            field=models.ImageField(upload_to='static/catalogos/img', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='caratula',
            field=models.ImageField(upload_to='static/catalogos/img', verbose_name='Caratula'),
        ),
    ]
