# Generated by Django 4.0.4 on 2022-05-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_alter_distribuidorajuego_logodistribuidora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='annoSalida',
            field=models.IntegerField(max_length=20, verbose_name='AnnoSalida'),
        ),
    ]
