# Generated by Django 4.0.4 on 2022-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_juego_annosalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='annoSalida',
            field=models.IntegerField(verbose_name='Año salida:'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='caratula',
            field=models.ImageField(upload_to='catalogos/static/catalogos/img', verbose_name='Caratula:'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripcion:'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=20, verbose_name='Titulo:'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='widget',
            field=models.CharField(max_length=100, verbose_name='Iframe:'),
        ),
    ]
