# Generated by Django 4.0.4 on 2022-05-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_alter_juego_annosalida_alter_juego_caratula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripcion:'),
        ),
    ]
