# Generated by Django 4.0.1 on 2022-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_alter_juego_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='annoSalida',
            field=models.CharField(max_length=4, verbose_name='Año salida:'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo:'),
        ),
    ]
