# Generated by Django 4.0.1 on 2022-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_alter_juego_annosalida_alter_juego_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='annoSalida',
            field=models.IntegerField(verbose_name='Año salida:'),
        ),
    ]
