# Generated by Django 4.0.4 on 2022-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='idClasificacion',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
