# Generated by Django 4.0.4 on 2022-06-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0019_alter_clasificacion_idclasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacion',
            name='idClasificacion',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='juego',
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='idClasificacionJuego',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalogos.juego', verbose_name='id'),
            preserve_default=False,
        ),
    ]
