# Generated by Django 4.0.4 on 2022-06-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_remove_clasificacion_idclasificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacion',
            old_name='idClasificacionJuego',
            new_name='idClasificacion',
        ),
    ]
