# Generated by Django 4.0.4 on 2022-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0022_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de actualizacion:'),
        ),
    ]
