# Generated by Django 4.0.4 on 2022-06-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0023_alter_clasificacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
            ],
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='pais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogos.paises', verbose_name='Pais:'),
        ),
    ]
