# Generated by Django 4.0.4 on 2022-06-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0024_paises_alter_clasificacion_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='Pais'),
        ),
    ]
