# Generated by Django 4.0.4 on 2022-06-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0025_alter_clasificacion_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='pais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogos.paises', verbose_name='Pais:'),
        ),
    ]
