# Generated by Django 4.0.4 on 2022-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0027_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock:'),
            preserve_default=False,
        ),
    ]
