# Generated by Django 4.0.4 on 2022-07-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0028_juego_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='id:')),
                ('comprador', models.CharField(max_length=100, verbose_name='Comprador:')),
                ('estado', models.IntegerField(verbose_name='Estado de la compra:')),
                ('total', models.IntegerField(verbose_name='Precio de la compra:')),
                ('articulos', models.CharField(max_length=100, verbose_name='Comprador:')),
            ],
        ),
    ]
