# Generated by Django 4.0.4 on 2022-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='articulos',
            field=models.CharField(max_length=100, verbose_name='compras:'),
        ),
    ]
