# Generated by Django 4.0.4 on 2022-07-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0031_compras_estimacionllegada_compras_fechacompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='estimacionllegada',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='fechaCompra',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='fechallegada',
        ),
    ]
