# Generated by Django 4.0.4 on 2022-07-10 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextrainfo',
            name='username_id',
        ),
        migrations.AddField(
            model_name='userextrainfo',
            name='id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id'),
            preserve_default=False,
        ),
    ]
